openapi: 3.0.0
paths:
  /users:
    get:
      operationId: UserController_fetchUsers
      parameters:
        - name: name
          required: false
          in: query
          schema:
            type: string
        - name: size
          required: false
          in: query
          schema:
            type: number
        - name: page
          required: false
          in: query
          schema:
            type: number
      responses:
        '200':
          description: user list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserEntity'
      security: &ref_0
        - basic: []
    post:
      operationId: UserController_createUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: user created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEntity'
      security: *ref_0
  /users/{id}:
    get:
      operationId: UserController_fetchUser
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '200':
          description: user detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserEntity'
      security: *ref_0
    put:
      operationId: UserController_updateUser
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserDto'
      responses:
        '204':
          description: user updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
      security: *ref_0
    delete:
      operationId: UserController_deleteUser
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: number
      responses:
        '204':
          description: user deleted
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
      security: *ref_0
info:
  title: Api Example
  description: The API description
  version: '1.0'
  contact: {}
tags:
  - name: user
    description: ''
servers: []
components:
  schemas:
    UserEntity:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        age:
          type: number
      required:
        - id
        - name
        - age
    CreateUserDto:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
      required:
        - name
        - age
    UpdateUserDto:
      type: object
      properties:
        name:
          type: string
        age:
          type: number
