openapi: 3.1.0
info:
  title: Example Open Api Types
  version: '1.0'
  contact:
    email: example@example.com
    name: example
    url: https://github.com/tkow/nestjs-openapi-template
  description: Example of Open Api Types
  license:
    name: MIT
paths:
  user/{id}:
    post:
      operationId: test
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
  users:
    users:
      get:
        responses:
          default:
            description: user list
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/UserEntity'
        requestBody:
          content:
            application/json:
              schema:
                type: object
                title: test
components: {}
